### ISSUE TITLE
can not use Gog version?

### ISSUE THREAD

**Issue by legluondunet** [wheybags/freeablo#432] opened 2019-03-23 16:36 UTC
Hello,
I just bought Gog version but freeablo does not recognize the files:

```
$ ./freeablo 
Unrecognised version of Diablo.exe
skipping stormlib init - won't be able to read files in MPQ archives
Unrecognised version of Diablo.exe
skipping stormlib init - won't be able to read files in MPQ archives
```
Thank you for your help.

**Comment by AJenbo** [comment] 2019-03-23 16:45
@legluondunet could you provide the MD5s of the two Diablo.exe files in the GOG version. are identical to 1.09 except for a digintal signature (and a hacked .rsrc and two stubbed calls in the dx versions case) so should work fine if just added to Freeablo's whitelist.

**Comment by legluondunet** [comment] 2019-03-23 18:15
@AJenbo you are working several Diablo project?

This is the MD5 from Diablo Gog edition files:
DIABDAT.MPQ: 011bc6518e6166206231080a4440b373
Diablo.exe: 2b5cdb5e0caf5dc43c8fa6fa4d6255b5

**Comment by AJenbo** [comment] 2019-03-23 18:38
Only Devilution and DevilutionX, but I try to share relevant info with Freeablo

Looks like this is a duplicate of #255

**Comment by wheybags** [comment] 2019-03-26 07:52
Since it looks like the offsets in the binary should be all the same as v1.09, it's probably just a matter of adding a symlink and setting up the versions.ini file here https://github.com/wheybags/freeablo/tree/master/resources/exeversions
There's a similar thing for v1.09b already, it's just the same as v1.09
There is a separate executable defined in the cmake files called exedump, which should read everything we currently know hopw to read and dump it as text
so that can be used to make sure it's working

**Comment by alanhaugen** [comment] 2019-03-31 07:40
Please add following

in
resources/exeversions/versions.ini:
v109bgog=2b5cdb5e0caf5dc43c8fa6fa4d6255b5

then
cp resources/exeversions/v109b.ini resources/exeversions/v109bgog.ini

**Comment by legluondunet** [comment] 2019-03-31 09:28
Thank you @alanhaugen , I can launch the game now.
But is it normal:
- no cinematics at start
- I can not register my player name
- I can not talk to pnj
- can not save or load game
...

**Comment by wheybags** [comment] 2019-03-31 18:13
You should be able to save (load just checks if there is a save file and trys to laod it), and you shpould be able to talk to npcs. Other than that, no

**Closed** 2019-03-31 18:12 UTC
Labels: good first issue
